//
//  DetailWorker.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 25.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    
    var isPaginating: Bool = false

    func getMovieList(genreId: String, page: String, pagination: Bool = false, successCompletion: @escaping ((Movie?, String?) -> Void) ) {
        
        if pagination {
            isPaginating = true
        }
        
        let path = ApiUrls.movieListUrl + "&page=" + page
        let urlPath = ApiUrls.moviesAdditionals + genreId
        let url = path + urlPath
                
        NetworkManager.shared.request(type: Movie.self, url: url, method: .get) { (response) in
            
            switch response {
            case .success(let result):
                successCompletion(result,nil)
            case .failure(let error):
                print(error.localizedDescription)
                successCompletion(nil,error.localizedDescription)
            }
            if pagination {
                self.isPaginating = false
                
            }
           
        }
        
    }
    
    
}
