//
//  DetailRouter.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 25.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic {
    func routeToVideoPlayer(movieName: String)
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    
}

protocol DetailDataPassing {
    
    var dataStore: DetailDataStore? { get }
    
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing {
 
    weak var viewController: DetailViewController?
  
    var dataStore: DetailDataStore?
    
    func routeToVideoPlayer(movieName: String) {
        let vc = VideoPlayerViewController()
        vc.movieName = movieName
        viewController?.navigationController?.pushViewController(vc, animated: true)
    
    }

    
}
