//
//  HomeModels.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 25.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  // MARK: Use cases
  
  enum FetchGenres
    {
      struct Request
      {
          
      }
      struct Response
      {
          var genres: [Genre]
      }
      struct ViewModel
      {
          struct DisplayedGenres {
              let id: Int
              let name: String
          }
          var displayedGenre: [DisplayedGenres]
          
      }
      
  }
    
    enum FetchMovies {
        struct Request {
            
        }
        struct Response {
            var movies : [MovieResult]
        }
        
        struct ViewModel {
            struct DisplayedMovies {
                let title: String
                let posterPath: String
                let backdropPath: String
            }
            var displayedMovieList: [DisplayedMovies]
        }
    }
    
    enum FetchSlider {
        struct Request {
            
        }
        struct Response {
            var sliders: [SliderResult]
        }
        
        struct ViewModel {
            struct DisplayedSliders {
                let title: String
                let posterPath: String
                let backdropPath: String
            }
            var displayedSliders: [DisplayedSliders]
        }
    }
    
}
