//
//  HomeRouter.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 25.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToMovielistDetail(genreId: String, genreName: String)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
    
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {

    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
  
    func routeToMovielistDetail(genreId: String, genreName: String) {
        let vc = DetailViewController()
        vc.genreid = genreId
        vc.genreName = genreName
        vc.modalPresentationStyle = .fullScreen
        viewController?.navigationController?.pushViewController(vc, animated: true)
        
    }
    
    
}
