//
//  VideoPlayerPresenter.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 27.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VideoPlayerPresentationLogic {
 
    func presentVideoPlayer(response: VideoPlayer.FetchVideo.Response)
}

class VideoPlayerPresenter: VideoPlayerPresentationLogic {
    
    weak var viewController: VideoPlayerDisplayLogic?
    
    // MARK: Do something
    func presentVideoPlayer(response: VideoPlayer.FetchVideo.Response) {
        let displayedViewModel = VideoPlayer.FetchVideo.ViewModel.displayVideoPlayerViewModel(showVideoUrl: response.videoUrl)
        
        let viewModel = VideoPlayer.FetchVideo.ViewModel(displayedViewModel: displayedViewModel)
        
        viewController?.displayVideo(viewModel: viewModel)
    }

    
}
