//
//  VideoPlayerModels.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 27.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum VideoPlayer
{
  // MARK: Use cases
  
  enum FetchVideo
  {
    struct Request
    {
        
    }
    struct Response
    {
        var videoUrl: String
    }
    struct ViewModel
    {
        struct displayVideoPlayerViewModel {
            let showVideoUrl: String
        }
        
        var displayedViewModel: displayVideoPlayerViewModel
        
    }
      
  }
    
}
