//
//  VideoPlayerInteractor.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 27.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VideoPlayerBusinessLogic {
    func playerVideoRequest(request: VideoPlayer.FetchVideo.Request)
    
}

protocol VideoPlayerDataStore {
    //var name: String { get set }
    
}

class VideoPlayerInteractor: VideoPlayerBusinessLogic, VideoPlayerDataStore {
    
    var presenter: VideoPlayerPresentationLogic?
    var worker: VideoPlayerWorker?
    
    func playerVideoRequest(request: VideoPlayer.FetchVideo.Request) {
        
        worker = VideoPlayerWorker()
        worker?.doSomeWork()
        
        let url = VideoUrls.videoUrl
        
        let response = VideoPlayer.FetchVideo.Response(videoUrl: url)
        
        presenter?.presentVideoPlayer(response: response)
        
    }
    
}
