//
//  VideoPlayerRouter.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 27.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VideoPlayerRoutingLogic {
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol VideoPlayerDataPassing {
    
    var dataStore: VideoPlayerDataStore? { get }
    
}

class VideoPlayerRouter: NSObject, VideoPlayerRoutingLogic, VideoPlayerDataPassing {
 
    weak var viewController: VideoPlayerViewController?
    var dataStore: VideoPlayerDataStore?
  
  
    
}
