//
//  SplashViewController.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 25.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Lottie

protocol SplashDisplayLogic: AnyObject {
    
    func displaySomething(viewModel: Splash.Something.ViewModel.ReachabilityViewModel)    
}

class SplashViewController: UIViewController, SplashDisplayLogic {
    
    var interactor: SplashBusinessLogic?
    var router: (NSObjectProtocol & SplashRoutingLogic & SplashDataPassing)?
    private var animationView: LottieAnimationView?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = SplashInteractor()
        let presenter = SplashPresenter()
        let router = SplashRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .white
        configureInteractor()
        layout()
    }

    func configureInteractor() {
        let request = Splash.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: Splash.Something.ViewModel.ReachabilityViewModel) {
        if viewModel.isReachable {
            router?.navigateToHome()
        }
        else {
            Utils.shared.showPopup(title: "Warning!", message: viewModel.networkStatus, view: self)
        }
    }
    
}

extension SplashViewController {
    
    func layout() {
        view.backgroundColor = .white
        configureAnimation()
    }
    
    func configureAnimation() {
        animationView = .init(name: "data")
        animationView!.frame = view.bounds
        animationView!.contentMode = .scaleAspectFit
        animationView!.loopMode = .loop
        animationView!.animationSpeed = 0.5
        view.addSubview(animationView!)
        animationView!.play()
    }
    
}
