//
//  SplashRouter.swift
//  VideoPlayerApp
//
//  Created by bora ateş on 25.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
    func navigateToHome()
}

protocol SplashDataPassing {

    var dataStore: SplashDataStore? { get }
}

class SplashRouter: NSObject, SplashRoutingLogic, SplashDataPassing {
      
    weak var viewController: SplashViewController?
  
    var dataStore: SplashDataStore?
  
    func navigateToHome() {
        DispatchQueue.main.asyncAfter(deadline: .now()+5 ) {
            let vc = HomeViewController()
            let nav = UINavigationController(rootViewController: vc)
            nav.modalPresentationStyle = .fullScreen
            self.viewController?.present(nav, animated: true)
        }
    }
        
    
}
